apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysql-password: {{ .Values.mysql.password }}
  mysql-root-password: {{ .Values.mysql.rootPassword }}
