name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: 0xsaju
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 0xsaju/mysql-deployment-test:${{ github.sha }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v1

    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        sed -i "s/127.0.0.1/${{ secrets.K3S_HOST }}/g" ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to k3s
      run: |
        helm upgrade --install flask-app ./charts/flask-app \
          --namespace flask-app \
          --create-namespace \
          --set image.repository=0xsaju/mysql-deployment-test \
          --set image.tag=${{ github.sha }}
